### ISSUE TITLE
code-server版本vscode搜不到raccoon

### ISSUE THREAD

**Issue by nfyxhan** [SenseTime-Copilot/Raccoon#12]
![image](https://github.com/SenseTime-Copilot/Raccoon/assets/15644272/b727c4a2-e579-4d1f-a978-df5f445a6c35)
```
code-server --version
4.16.1 94ef3776ad7bebfb5780dfc9632e04d20d5c9a6c with Code 1.80.2
```
https://github.com/coder/code-server/

**Comment by todd-xander** [comment]
code server 使用OpenVSIX作为市场，可以先从微软市场下载包后手动安装。
我们尽快安排上线OpenVSIX。

**Comment by todd-xander** [comment]
> code server 使用OpenVSIX作为市场，可以先从微软市场下载包后手动安装。 我们尽快安排上线OpenVSIX。

以发布，可以尝试一下
