### ISSUE TITLE
canot use when click the Raccoon tab!

### ISSUE THREAD

**Issue by liuwq999** [SenseTime-Copilot/Raccoon#5]
I got the error message.

**Comment by liuwq999** [comment]
Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Comment by todd-xander** [comment]
抱歉，是点击raccon提供的文件格式文档时吗？能否提供截图帮助我们更好的定位问题

**Comment by ziyouzhea** [comment]
重启后可以了
