### ISSUE TITLE
[Feedback]log in error

### ISSUE THREAD

**Issue by yayaya-pro** [SenseTime-Copilot/Raccoon#61]
Type: <b>Bug</b>

登录失败。提示客户端错误

Extension version: 0.70.6
VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13500H (16 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (2.95GB free)|
|Process Argv|--crash-reporter-id 1b14d949-c7c6-44c2-8a41-83023944e63f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31022790
dwnewjupytercf:31035177

```

</details>

**Comment by yayaya-pro** [comment]
Login Failed: Client network socket disconnected
before secure TLS connection was established

**Comment by todd-xander** [comment]
可能是网络代理或防火墙问题，或者方便加微信远程一下吗

![mmexport1714969572033](https://github.com/SenseTime-Copilot/Raccoon/assets/4033805/201d0fc5-4341-432e-988d-0451a58826a3)

**Comment by yayaya-pro** [comment]
我通过卸载重装已解决问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhang ***@***.***&gt;; 
发送时间: 2024年5月6日(星期一) 中午12:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SenseTime-Copilot/Raccoon] [Feedback]log in error (Issue #61)














 
可能是网络代理或防火墙问题，或者方便加微信远程一下吗
 
mmexport1714969572033.jpg (view on web)
