### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by bool2007** [SenseTime-Copilot/Raccoon#8]
登陆按键一直是灰色，无法点击，换了电脑也是无法点击登录按键。

**Comment by todd-xander** [comment]
是在填写了正确用户名和密码后，按钮依旧不可用吗

**Comment by bool2007** [comment]
是的

**Comment by bool2007** [comment]
> 是在填写了正确用户名和密码后，按钮依旧不可用吗

公司电脑不能登录，登录按键一直是灰的。自己电脑可以，输入一定长度后变为可点。

**Comment by bool2007** [comment]
> > > 是在填写了正确用户名和密码后，按钮依旧不可用吗
> > 
> > 
> > 公司电脑不能登录，登录按键一直是灰的。自己电脑可以，输入一定长度后变为可点。
> 
> @bool2007 可以尝试升级插件至0.62.4版本看是否能够解决

已经可以了   谢谢
