### ISSUE TITLE
在github.dev上使用vscode插件无法登录

### ISSUE THREAD

**Issue by nfyxhan** [SenseTime-Copilot/Raccoon#9]
![image](https://github.com/SenseTime-Copilot/Raccoon/assets/15644272/34260f60-3c20-4856-aa62-0c6b294c8870)
版本信息  
![image](https://github.com/SenseTime-Copilot/Raccoon/assets/15644272/22811a20-83e5-4f07-a0af-5f28bbfde851)

**Comment by nfyxhan** [comment]
![image](https://github.com/SenseTime-Copilot/Raccoon/assets/15644272/17d65335-055d-453a-8cc0-7e1fa042dc8a)
![image](https://github.com/SenseTime-Copilot/Raccoon/assets/15644272/e1fd7bd8-9283-4482-9bc1-60232cd5ccb6)
![image](https://github.com/SenseTime-Copilot/Raccoon/assets/15644272/a5215d11-d6dd-4a0f-b2a3-47946b574336)

**Comment by liuwq999** [comment]
加载 Web 视图时出错: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Comment by liuwq999** [comment]
目前更新到最新版0.62.4，出现这个信息

**Comment by liuwq999** [comment]
通过如下方式解决了。1、关闭vscode
2、win+R 输入cmd ，命令行输入以下命令
code --no-sandbox重启vscode

**Comment by todd-xander** [comment]
> ![image](https://private-user-images.githubusercontent.com/15644272/296670297-17d65335-055d-453a-8cc0-7e1fa042dc8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDU2NDIsIm5iZiI6MTcwNTM0NTM0MiwicGF0aCI6Ii8xNTY0NDI3Mi8yOTY2NzAyOTctMTdkNjUzMzUtMDU1ZC00NTNhLThjYzAtN2UxZmEwNDJkYzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYWQ1Y2QxMTk1MDkxZjcxNWEwMDkwOGYwZDI0MWFhMTQ1YWNjNDJkNWRkNjEwZWI2NzE0YmNmMGE4NzhkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yVchI4zPh13B5s9qHgxRI4PRBDBdn0yjP_aiV14QeVQ) ![image](https://private-user-images.githubusercontent.com/15644272/296670338-e1fd7bd8-9283-4482-9bc1-60232cd5ccb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDU2NDIsIm5iZiI6MTcwNTM0NTM0MiwicGF0aCI6Ii8xNTY0NDI3Mi8yOTY2NzAzMzgtZTFmZDdiZDgtOTI4My00NDgyLTliYzEtNjAyMzJjZDVjY2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ODgxY2U2ZjVhZTg1ZDhmMzQwY2NiM2QzYTU3ZmFlMGI0N2ZkOWMyMDcwM2JlMzExNTY2MjdlMjU3MDRlNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qSwCqFNwm3ksxOU4N_udO8JFluZJGe8EQqn0yzizGEg) ![image](https://private-user-images.githubusercontent.com/15644272/296670374-a5215d11-d6dd-4a0f-b2a3-47946b574336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDU2NDIsIm5iZiI6MTcwNTM0NTM0MiwicGF0aCI6Ii8xNTY0NDI3Mi8yOTY2NzAzNzQtYTUyMTVkMTEtZDZkZC00YTBmLWIyYTMtNDc5NDZiNTc0MzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YzFjZWJiMWMzYjlhOGJhZDIzNTQ3YmU1ZmRlNjNhYmQ1MzYxNTljMmIzNTQ3YzYzNmY3ODQ1NWZjMTM1NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PNTYkH8h1frN9WSF8c5kPP7Id0vTwUvS0Q03SxMiys)

@nfyxhan 可以尝试下Ctrl+Shift+P，选择 Raccoon: Reset all settings 重置下看看是否可以解决。

**Comment by nfyxhan** [comment]
> > ![image](https://private-user-images.githubusercontent.com/15644272/296670297-17d65335-055d-453a-8cc0-7e1fa042dc8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDU2NDIsIm5iZiI6MTcwNTM0NTM0MiwicGF0aCI6Ii8xNTY0NDI3Mi8yOTY2NzAyOTctMTdkNjUzMzUtMDU1ZC00NTNhLThjYzAtN2UxZmEwNDJkYzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYWQ1Y2QxMTk1MDkxZjcxNWEwMDkwOGYwZDI0MWFhMTQ1YWNjNDJkNWRkNjEwZWI2NzE0YmNmMGE4NzhkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yVchI4zPh13B5s9qHgxRI4PRBDBdn0yjP_aiV14QeVQ) ![image](https://private-user-images.githubusercontent.com/15644272/296670338-e1fd7bd8-9283-4482-9bc1-60232cd5ccb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDU2NDIsIm5iZiI6MTcwNTM0NTM0MiwicGF0aCI6Ii8xNTY0NDI3Mi8yOTY2NzAzMzgtZTFmZDdiZDgtOTI4My00NDgyLTliYzEtNjAyMzJjZDVjY2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ODgxY2U2ZjVhZTg1ZDhmMzQwY2NiM2QzYTU3ZmFlMGI0N2ZkOWMyMDcwM2JlMzExNTY2MjdlMjU3MDRlNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qSwCqFNwm3ksxOU4N_udO8JFluZJGe8EQqn0yzizGEg) ![image](https://private-user-images.githubusercontent.com/15644272/296670374-a5215d11-d6dd-4a0f-b2a3-47946b574336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDU2NDIsIm5iZiI6MTcwNTM0NTM0MiwicGF0aCI6Ii8xNTY0NDI3Mi8yOTY2NzAzNzQtYTUyMTVkMTEtZDZkZC00YTBmLWIyYTMtNDc5NDZiNTc0MzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YzFjZWJiMWMzYjlhOGJhZDIzNTQ3YmU1ZmRlNjNhYmQ1MzYxNTljMmIzNTQ3YzYzNmY3ODQ1NWZjMTM1NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PNTYkH8h1frN9WSF8c5kPP7Id0vTwUvS0Q03SxMiys)
> 
> @nfyxhan 可以尝试下Ctrl+Shift+P，选择 Raccoon: Reset all settings 重置下看看是否可以解决。

还是一样的报错

**Comment by todd-xander** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/15644272/296670297-17d65335-055d-453a-8cc0-7e1fa042dc8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDU2NDIsIm5iZiI6MTcwNTM0NTM0MiwicGF0aCI6Ii8xNTY0NDI3Mi8yOTY2NzAyOTctMTdkNjUzMzUtMDU1ZC00NTNhLThjYzAtN2UxZmEwNDJkYzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYWQ1Y2QxMTk1MDkxZjcxNWEwMDkwOGYwZDI0MWFhMTQ1YWNjNDJkNWRkNjEwZWI2NzE0YmNmMGE4NzhkNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yVchI4zPh13B5s9qHgxRI4PRBDBdn0yjP_aiV14QeVQ) ![image](https://private-user-images.githubusercontent.com/15644272/296670338-e1fd7bd8-9283-4482-9bc1-60232cd5ccb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDU2NDIsIm5iZiI6MTcwNTM0NTM0MiwicGF0aCI6Ii8xNTY0NDI3Mi8yOTY2NzAzMzgtZTFmZDdiZDgtOTI4My00NDgyLTliYzEtNjAyMzJjZDVjY2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ODgxY2U2ZjVhZTg1ZDhmMzQwY2NiM2QzYTU3ZmFlMGI0N2ZkOWMyMDcwM2JlMzExNTY2MjdlMjU3MDRlNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qSwCqFNwm3ksxOU4N_udO8JFluZJGe8EQqn0yzizGEg) ![image](https://private-user-images.githubusercontent.com/15644272/296670374-a5215d11-d6dd-4a0f-b2a3-47946b574336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDU2NDIsIm5iZiI6MTcwNTM0NTM0MiwicGF0aCI6Ii8xNTY0NDI3Mi8yOTY2NzAzNzQtYTUyMTVkMTEtZDZkZC00YTBmLWIyYTMtNDc5NDZiNTc0MzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YzFjZWJiMWMzYjlhOGJhZDIzNTQ3YmU1ZmRlNjNhYmQ1MzYxNTljMmIzNTQ3YzYzNmY3ODQ1NWZjMTM1NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PNTYkH8h1frN9WSF8c5kPP7Id0vTwUvS0Q03SxMiys)
> > 
> > 
> > @nfyxhan 可以尝试下Ctrl+Shift+P，选择 Raccoon: Reset all settings 重置下看看是否可以解决。
> 
> 还是一样的报错，不知道和我用的https://github.dev 有没有关系

多谢提供的信息，github.dev上复现了这个问题，我们尽快修复一下

**Comment by todd-xander** [comment]
@nfyxhan 可以优先尝试一下为web适配的版本，这个版本由于axios的xianzhi限制，web端暂时不支持流式输出，对于聊天结果，需要等待回复完成后显示。
[raccoon-0.62.5.vsix.zip](https://github.com/SenseTime-Copilot/Raccoon/files/14099959/raccoon-0.62.5.vsix.zip)
